### PR TITLE
add source app info to notifications

### PR DESCRIPTION
**Pull request by Strubbl**
This commit adds the information to a notification that wallabag is the
source of that notification. Otherwise notification from similar apps
cannot be distinguished.

### CODE REVIEW

**Comment by di72nn** [comment]
Maybe add a colon after the app name?

**Comment by Strubbl** [comment]
> Maybe add a colon after the app name?

Yes i would like to, but the french people add a space before the colon, german ones usually do not. That's why i left it out. 
any idea for a general divider?

//cc @nicosomb @tcitworld

**Comment by tcitworld** [comment]
Doesn't matter much. Anyway, on Android 7.1 the notifications show up from which app they come from :

**Comment by di72nn** [comment]
> any idea for a general divider?

Hyphen / minus sign / dash?

> Then we should prepend app name only if Android version <= 6 (?).

on Android 7.1 the notifications show up from which app they come from

**Comment by tcitworld** [comment]
@Strubbl Please add an hyphen. :)

**Comment by Strubbl** [comment]
Yes, if i am back to my android development PC i am going to do that. Currently i have only a notebook with me. And i think a middle dot (this one · ) is going to be better than a hyphen. And i also need to add the android api version IF

**Comment by tcitworld** [comment]
Ping @Strubbl

**Comment by Strubbl** [comment]
changes implemented. I have used the middle dot and i hope this is okay? It is smaller compared to a hyphen or the like. Also the wallabag app name is only added when using Android version before Nougat.

**Comment by tcitworld** [comment]
Restarting the build, travis had an issue.

**Pull request merged**
