### PR TITLE
Show preview picture in article view

### PR DESCRIPTION
**Pull request by di72nn**
#232.

Please somebody test image caching.

### CODE REVIEW

**Comment by ngosang** [comment]
It works for me! Thank you

**Comment by di72nn** [comment]
@ngosang if the images were downloaded previously, they won't be redownloaded just for previews. Did you try it with newly added articles?

I'll think about adding a hook to invalidate "images cached" flags for all the articles.

**Comment by ngosang** [comment]
> Did you try it with newly added articles?

I added new articles but nothing.. 😞

**Comment by di72nn** [comment]
Should be ok now (was caused by #543).

**Comment by Strubbl** [comment]
Just tested with http://sixactualites.fr/high-tech/hubble-etonne-decouverte-dune-lune-gravitant-autour-de-planete-makemake/27331
Offline support for preview image Works okay now.

**Pull request merged**
