### PR TITLE
Updated quote style

### LINKED ISSUE #1141: Updated quote style
Hi, I have some draft changes to the quote style making them closer to the style on the Wallabag web service.

eg. From ...

image

To ...

image

Is that of interest? I can send through a PR. `pre` blocks are unchanged.

### PR DESCRIPTION
**Pull request by creywood**
Edit: Now better integrated at #1165

~~As discussed at #1141, the updated style aims to be more easily identified as a quote and is more closely matched to the Wallabag web service style.~~

~~Closes #1141.~~

### CODE REVIEW

**Comment by di72nn** [comment]
Sorry for the delay and thank you for the PR!

Any idea why the height of the area marked with red is about twice the size of the area marked with green? Seems like the `p`'s `margin-bottom` causes it, but I'm not very experienced in CSS to tell for sure.

quote

Also, I'm testing your commit rebased on master, but I don't think it matters.

BTW, if you didn't know, you can use `chrome://inspect` in chromiun-based browsers to remotely inspect the WebView content of debug builds of the app.

**Comment by di72nn** [comment]
Compared with wallabag's web UI - seems like it has something to do with "collapsing margins" not collapsing. Not something I know how to handle.

**Comment by di72nn** [comment]
No, you're right, the problem is present in our current style too. We can merge this and fix the problem separately.

**Review by di72nn — APPROVED** [review]
Seems fine, but CSS is not my strength.

The CI status doesn't matter - the job was ran against master when it has an issue (#1142).

**Comment by di72nn** [comment]
Do not merge. Probably replaced with #1165.

**Comment by Strubbl** [comment]
I think we can close this in favor of #1165. Or did i overlook something this PR fulfills, which the other doesnt?

**Pull request closed without merging**
