### PR TITLE
Allow cleartext network traffic on Android 9

### PR DESCRIPTION
**Pull request by GeorgeHahn**
Address https://github.com/wallabag/android-app/issues/761.

<s>Please note that this is untested - I don't have an android dev setup available at the moment. I can test this out later if desired.</s>

Edit: Tested using the build linked below - this change functions correctly.

### CODE REVIEW

**Comment by Strubbl** [comment]
It would be nice if somebody can test this before we merge it. I have no wallabag instance running on http only.

Who can help here?

**Comment by jpalczewski** [comment]
I'll test it in a few days - I have a dockerized wallabag over http via https(traefik + letsencrypt). Unfortunately got that issue. 

By the way - is there any way to steal apk from travis,

**Comment by Strubbl** [comment]
It would be nice to get an apk from CI, but i am not aware that this is anyhow possible.

**Comment by GeorgeHahn** [comment]
I'd be happy to test this, but I haven't had time to setup an android build system locally.

It looks like Travis will only store artifacts if it has been connected to an S3 bucket.

**Comment by tcitworld** [comment]
To me it makes sense to enforce encrypted network traffic, since it's 2019 and Let's Encrypt makes it quite easy to add certs everywhere.

I would be fine with this option being set programmatically through settings, but it doesn't seem to be possible.

However I won't oppose this, especially if https://github.com/wallabag/android-app/issues/761#issuecomment-463092250 give me good reasons.

**Comment by tcitworld** [comment]
You can test this PR by installing the debug APK (it should install alongside your production wallabag app) available at https://framadrop.org/r/Eu3as-Ug1r#5+Mzf+1axX+r0fAAgPZ/FCCRNg04wyr8DoEORuPge+w=

**Comment by GeorgeHahn** [comment]
Confirmed - that build works for me. Thanks for building that!

**Comment by SkYNewZ** [comment]
I confirm that work for me too!

**Comment by GeorgeHahn** [comment]
Any blockers to getting this merged?

**Comment by jpalczewski** [comment]
I linked to this PR from another open-source app, but I'll add comment here too - this may involve some in-depth analysis of both projects source code, but maybe someone is interested. 

Wallabag doesn't allow to even login into server, when firefly app allows to login and do some actions, only sometimes refusing due to network policy. That weird, because settings(both webapps as docker images behind traefik that handles LE certificates) is same in two situations. 

Maybe it is related with different languages, maybe it may be a bug in Android itself, or it allows to communicate to cleartext-over-TLS cases through different APIs.

@tcitworld maybe a simple warning when tested(not string written by user, but resulting URL after possible redirections server-side) server address is really clear-text only may be a good idea while disabling system-provided security.

**Comment by Strubbl** [comment]
From my point of view we can merge this. @tcitworld had some doubts w.r.t. security i think. 

@tcitworld what do you think? i would like to merge this PR

**Comment by Strubbl** [comment]
@jpalczewski a traefik solution to make wallabag app can be found here: https://github.com/wallabag/android-app/issues/756#issuecomment-462996975

**Comment by norweeg** [comment]
instead of allowing cleartext network traffic, why not fix the web application and have it honor the [X-Forwarded-Proto header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto) when redirecting requests?

**Comment by GeorgeHahn** [comment]
This change brings Android 9 behavior in line with the behavior of Android <8. This PR is primarily focused on solving #761 - allowing the app to be used for people who host servers on their local networks.

It may be worth having a conversation about explicitly disallowing unencrypted communications, but I believe that conversation is out of scope for this PR & the accompanying issue.

**Comment by Strubbl** [comment]
ping @tcitworld for my comment above https://github.com/wallabag/android-app/pull/762#issuecomment-467158856

**Comment by tcitworld** [comment]
Let's merge this. I'd like a warning on the connection assistant when using cleartext though.

**Pull request merged**
