### PR TITLE
TTS (Text to Speech) Support (Issue #5)

### PR DESCRIPTION
**Pull request by tyndare**
Patch proposition to add a support for Text To Speech
https://github.com/wallabag/android-app/issues/5

### CODE REVIEW

**Comment by tcitworld** [comment]
Can you rebase your PR ? wallabag v2 compatibility has been added.

**Comment by tyndare** [comment]
Yes, I'll do it on Monday.

**Comment by tyndare** [comment]
I rebased it.

**Comment by tcitworld** [comment]
Thanks a lot !

**Pull request merged**
