### PR TITLE
Make icon adaptive

### PR DESCRIPTION
**Pull request by Nuntius0**
This makes the launcher icon adaptive on Android 8+.

I'm aware of [this issue](https://github.com/wallabag/android-app/issues/317), but since the process of designed a completely new icon should rightly take some time, I figured that I don't want Wallabag to stand out amongst all the other icons anymore by being forcibly square.

Let me know what you think :)

### CODE REVIEW

**Comment by Nuntius0** [comment]
This is the overview Android Studio gives about all the different flavors:

wallabag-icon-overview
(The dotted line is the _safe zone_, anything outside that might get cropped by the launcher)
(Being a screenshot, it's not very high quality, but at least you get the idea)

**Comment by Nuntius0** [comment]
I only saw the issue but not the [pull request](https://github.com/wallabag/android-app/pull/714/files) with the new icon. My bad!

**Comment by hellpe** [comment]
So has it been fixed? My launcher icon still looks like this on my phone (Android One 9, Mi A2 Lite):
Screenshot_20190809-120133

**Comment by Nuntius0** [comment]
No, the other open PR has unfortunately never been merged

**Pull request closed without merging**
