### PR TITLE
Update transtations

### PR DESCRIPTION
**Pull request by di72nn**

### CODE REVIEW

**Comment by tcitworld** [comment]
Strange that the German translation has one string less than Japanese or Russian.

**Comment by di72nn** [comment]
French, German and Spanish are not translated completely.

**Comment by tcitworld** [comment]
So is that an issue with Weblate committing `Currently translated at 100.0% (206 of 206 strings)` whereas there should be 207 ?

**Comment by di72nn** [comment]
I presume the reason is that the commit is old.

**Comment by tcitworld** [comment]
Right.

**Pull request merged**
