### PR TITLE
Update f-droid logo

### LINKED ISSUE #268: Use new F-Droid badge
See https://f-droid.org/posts/get-it-on-f-droid-badges/.

### PR DESCRIPTION
**Pull request by nicosomb**
Fix #268

### CODE REVIEW

**Comment by di72nn** [comment]
Margins should probably be removed. Now the badges are badly aligned: https://github.com/wallabag/android-app/blob/nicosomb-patch-1/README.md

**Comment by tcitworld** [comment]
ping @nicosomb

**Comment by nicosomb** [comment]
I used the original logo, hosted on their website. Do we need to edit it and host it?

**Comment by di72nn** [comment]
It seems the new Google Play badge have margins too:
[Google Play badge](https://play.google.com/intl/en_us/badges/)
So updating both badges should do the trick.

**Pull request merged**
