### PR TITLE
Explain how to setup Wallabag for the first time

### PR DESCRIPTION
**Pull request by gjedeer**

### CODE REVIEW

**Comment by gjedeer** [comment]
I was not able to set up this app without reading the source, so maybe a little instruction would help the less inquisitive

**Comment by tcitworld** [comment]
This will really change with the new versions of the app (currently in beta), but I accpet the merge.

**Comment by gjedeer** [comment]
Oh, cool, can't wait for it then.

**Comment by tcitworld** [comment]
You have a look at it on [Google Play](https://play.google.com/apps/testing/fr.gaulupeau.apps.InThePoche) or download the [apk file](https://github.com/wallabag/android-app/releases/tag/1.9-beta.5)

**Pull request merged**
