### PR TITLE
An updated color scheme

### PR DESCRIPTION
**Pull request by Lokesh-Krishna**
A new color scheme to go along with the new icon, as discussed at #317.
This also addresses #157.
Is this the right way to make such a change?

### CODE REVIEW

**Comment by Lokesh-Krishna** [comment]
Okay, I seemed to have made the same mistake I made in #389. Can someone please help me do this right?

**Comment by di72nn** [comment]
You based your `Lokesh-Krishna-colors` branch on your other branch. If you want your Pull Requests to be separate, you should base your changes on upstream changes (on the `master` branch of this repository in this case).
I'm not good at explaining it :/
If you plan to use git, I would recommend to read (at least selectively) [Pro Git](https://git-scm.com/book).

**Comment by Lokesh-Krishna** [comment]
Thanks a lot. I'll go through that book. I know I should have focused on learning the basics first but I was too excited. :see_no_evil: 

I think the mistake I made was that I initially made all my readme related commits to my master branch instead of making them to a separate branch and so now my master branch is ahead of this one by all those commits. I'll try reverting those changes and keeping my master branch clean and using separate branches for all my pull requests in the future.

Thank you so much for helping me figure this out. Should I close this pull request and submit a clean one then?

**Comment by Lokesh-Krishna** [comment]
Closing this to reopen later.

**Pull request closed without merging**
