### PR TITLE
Make highlight color different from background color

### PR DESCRIPTION
**Pull request by NWuensche**
In dark mode high contrast, the background color for selected text in an
article  and the normal background were both black.
Now gray is used for selected text background.

I'm not sure if this also closes bug #619. I think the big black box was fixed 
with the other dark mode adjustments I made before and the selected text 
background is fixed with this PR.

Can also someone tell me if the used gray is to similar to the background in 
normal dark mode? And if so, which color should I use?

### CODE REVIEW

**Comment by di72nn** [comment]
There seem to be several common approaches to highlighting, so I tried another one. I don't have personal preference.

This pull request changes | Inversion
--- | ---
Screenshot_20190820-151509_wallabag_pr | Screenshot_20190820-151802_wallabag_suggested
Screenshot_20190820-151530_wallabag_pr | Screenshot_20190820-152116_wallabag_suggested

Here's the code (I'm not very good with CSS, so...):
```CSS
::selection {
  color: #333;
  background: #FFF;
}

.high-contrast ::selection {
  color: #000;
}
```

And while we're at it, let's fix Solarized:

Current state | Inversion
--- | ---
Screenshot_20190820-151407_wallabag_current | Screenshot_20190820-151613_wallabag_suggested

Code:
```CSS
::selection {
  color: #fdf6e3; /* $base3 */
  background: #657B83; /* $base00 */
}
```

**Comment by NWuensche** [comment]
Should I just copy the css into the commit and rebase or are you going to create a new PR?

**Comment by di72nn** [comment]
You can just add the Solarized theme fix, but I'm not sure about the dark ones: I posted the screenshots to maybe get opinions.

**Comment by tcitworld** [comment]
The "inversion" solution seems fine to me.

**Comment by di72nn** [comment]
Let's go with inversion then.

**Comment by NWuensche** [comment]
Everything should be ready now.

**Pull request merged**
