### PR TITLE
fix tables, images and quotes in dark themes

### LINKED ISSUE #559: Dark theme: table rows have black font
It is really hard to read the black font on the dark background. I suggest changing the color to the one which is used for the article itself.

example article for testing the fix: http://www.techstage.de/test/Coda-Wireless-guenstiger-Bluetooth-Kopfhoerer-im-Test-3675740.html

screenshot of status quo:

screenshot_20170612-205646

### PR DESCRIPTION
**Pull request by ngosang**
Improves #562, fixes #559 Tested with dark and dark high contrast themes.

Tables: (Before, After)
http://www.techstage.de/test/Coda-Wireless-guenstiger-Bluetooth-Kopfhoerer-im-Test-3675740.html
screenshot_2017-06-18-11-23-20
screenshot_2017-06-18-12-14-55

https://github.com/open-guides/og-aws
screenshot_2017-06-18-11-25-06
screenshot_2017-06-18-11-57-19

Images with transparent backgound: (Before, After)
https://www.linux.com/blog/learn/chapter/Intro-to-Kubernetes/2017/5/set-cicd-pipeline-kubernetes-part-1-overview
screenshot_2017-06-18-11-26-17
screenshot_2017-06-18-11-34-09

Pre, quote blocks: (Before, After)
https://www.linux.com/blog/learn/chapter/Intro-to-Kubernetes/2017/5/set-cicd-pipeline-kubernetes-part-1-overview
screenshot_2017-06-18-12-00-23
screenshot_2017-06-18-11-56-36

### CODE REVIEW

**Comment by ngosang** [comment]
@Strubbl take a look

**Comment by ngosang** [comment]
Update: I reduced the table padding:
screenshot_2017-06-18-12-14-55

**Comment by di72nn** [comment]
The original articles (the first two examples) seem to have tables, but have poor presentation in wallabag web. Is it siteconfig's fault?

If you improve tables for the dark theme, shouldn't you also improve them for light ones?

**Comment by ngosang** [comment]
> The original articles (the first two examples) seem to have tables, but have poor presentation in wallabag web. 

Wallabag web uses different css styles

> Is it siteconfig's fault?

Not related

> If you improve tables for the dark theme, shouldn't you also improve them for light ones?

I can do after some feedback. I don't want to do the work if it isn't going to be merged.

**Comment by di72nn** [comment]
> Wallabag web uses different css styles

Maybe we should try to update app's styles with the styles from wallabag web? The CSS's in the app wasn't updated for ages.
Tables' styles can be improved in wallabag web too.


>> If you improve tables for the dark theme, shouldn't you also improve them for light ones?

> I can do after some feedback. I don't want to do the work if it isn't going to be merged.

Sorry, I got a wrong impression.

**Comment by Strubbl** [comment]
Thank you very much @ngosang 
This looks really good. I want to merge this in favor of my pull request. I really like your pull request, because it is only one clean commit, only changing the necessary lines. And of course it is cool that you already provided screenshots!

Yes, one could improve the light theme, too. But it is different theme and not related to the dark one. The point of this (or my PR) is, that the dark theme looks ugly when it comes to tables or source code markup.

Also, i do not get the relation to wallabag web. This is unrelated, as @ngosang pointed out. From wallabag web we only get the raw markup (HTML) via API and no CSS at all. Styling the content is the task of us. Wallabag web does not have a dark theme though we cannot merge their used css to us. 
Improving the wallabag web's style is task of the maintainer of the wallabag/wallabag repository. And I have seen, that there is already some activity by @jlnostr and @j0k3r . 

@di72nn is there anything which blocks us from merging this? Otherwise i would love to hit the "Merge pull request" button.

**Comment by di72nn** [comment]
I'm thankful too for your contribution @ngosang (but I tend to skip pleasantries, especially in case of recurring contributors).

> Yes, one could improve the light theme, too. But it is different theme and not related to the dark one. The point of this (or my PR) is, that the dark theme looks ugly when it comes to tables or source code markup.

> @di72nn is there anything which blocks us from merging this? Otherwise i would love to hit the "Merge pull request" button.

If the PR was only **fixing** a bug in dark themes (black fonts on dark background), it would be unrelated to light themes. But this PR also **improves** tables and `pre` elements. Such improvements should be consistent across themes.

> Also, i do not get the relation to wallabag web. ...

Correct, this is not directly related and I should've elaborated on that:
 * It may be a good idea to update app's styles from wallabag web styles (for consistency between web and Android views).
  This is not related to this PR at all, I only mention it because it is about styles too.
 * Currently the tables in wallabag web and Android views have pretty much the same presentation (and it isn't very good).
  @ngosang, can you consider also creating a PR (or checking if there is one already) for wallabag web to improve tables in the similar fashion? That's about consistency too.

**Comment by Strubbl** [comment]
> But this PR also **improves** tables and `pre` elements. Such improvements should be consistent across themes.

I do not agree. This statement conflicts with having different themes at all.


>   @ngosang, can you consider also creating a PR (or checking if there is one already) for wallabag web to improve tables in the similar fashion? That's about consistency too.

There is some activity by @jlnostr and @j0k3r for improving the style in the web page for sharing https://github.com/wallabag/wallabag/pull/3204. This is also completely unrelated to the dark style. 

Also the web style itself is completely unrelated. Since web is not an app on your smartphone those changes are completely unrelated. I do not care about consistency between sharing and web and app style. I would like to optimize for reading on my mobile. I think this conflicts with the web style.

**Comment by di72nn** [comment]
> What changes do you want also in light theme? pre and tables are already readable there.

Screenshots show implicit table cells (background, borders) that weren't present neither in dark themes, nor in light themes (and still absent in light themes). Last time I checked `pre` wasn't formatted correctly in light themes.

> Also the web style itself is completely unrelated. Since web is not an app on your smartphone those changes are completely unrelated. I do not care about consistency between sharing and web and app style. I would like to optimize for reading on my mobile. I think this conflicts with the web style.

I suggested to improve tables in the web version of wallabag which renders tables poorly (better than the Android app though). Relation: the same author can make similar changes.

@ngosang can you check why the first column in the first article is aligned by center? It seems the original article and wallabag web have it aligned by left.

**Comment by Strubbl** [comment]
>>What changes do you want also in light theme? pre and tables are already readable there.

>Screenshots show implicit table cells (background, borders) that weren't present neither in dark themes, nor in light themes (and still absent in light themes). Last time I checked pre wasn't formatted correctly in light themes.

@di72nn i opened #571 for you

> I suggested to improve tables in the web version of wallabag which renders tables poorly (better than the Android app though). Relation: the same author can make similar changes.

Can you please open an issue in the wallabag core repository if you want that change there?

> @ngosang can you check why the first column in the first article is aligned by center? It seems the original article and wallabag web have it aligned by left.

This has nothing to do with this pull request. Before this PR the table cells were aligned wrong. Now the tables cells are aligned still the same. Please open an issue for that so that we can investigate it later on.

**Comment by ngosang** [comment]
> can you check why the first column in the first article is aligned by center? It seems the original article and wallabag web have it aligned by left.

I updated this PR, It's fixed now. I also reduced the blockquote/pre padding a bit.

I'm going to open a PR to solve #571 (light and solariced themes) in few minutes. About the Wallabag web, well I don't have time now.

@di72nn Could you take a look at #552 and #558 (same bug)

screenshot_2017-06-20-03-44-36
screenshot_2017-06-20-03-46-55

**Comment by ngosang** [comment]
Update: I removed the table background color. In high contrast theme there is no difference but gray looks better to me.
Now:
screenshot_2017-06-20-04-20-43

Before:
screenshot_2017-06-18-12-14-55

**Comment by di72nn** [comment]
The tables look nice, thanks.

Codeblocks doesn't have `monospace` fonts though. Also, codeblocks in the dark theme (the not "contrast" one) maybe too contrast (black background).
I tried the following and it seems better (adding `#article` to `pre` seems to fix codeblocks):
```CSS
blockquote, pre {
  border: 1px solid #999;
  background: #222;
  padding: 0.25em;
  margin: 0;
}

.high-contrast blockquote, .high-contrast pre {
  background: #000;
}

#article pre {
  font-family: monospace;
  white-space: pre;
  text-justify: none;
}
```

**Comment by ngosang** [comment]
@di72nn I used the same black background color for "pre" that we were using for "blockquote". What about removing the background color and the border lines? Something like this?
screenshot_2017-06-21-19-04-33
screenshot_2017-06-21-19-04-03

**Comment by di72nn** [comment]
> I used the same black background color for "pre" that we were using for "blockquote".

Right. Then it was too contrast all along.

> What about removing the background color and the border lines?

It might be a matter of taste, but I like borders and different background more. Maybe make border lines a bit more subtle.

**Comment by ngosang** [comment]
@di72nn I updated the PR, take a look. If you agree this could be merged.
screenshot_2017-06-26-19-59-11
screenshot_2017-06-26-19-59-49

**Comment by di72nn** [comment]
Thanks again. Article view is an important part of the app and I very appreciate these improvements.

@Strubbl can you look at it and merge it if you're fine with it?

**Comment by Strubbl** [comment]
Thank you both!

**Pull request merged**
