### PR TITLE
Annotations support

### PR DESCRIPTION
**Pull request by di72nn**
Currently implemented:
 * Saving annotations (when updating from server).
 * Methods to work with annotations: `addAnnotation()`, `updateAnnotation()` and `deleteAnnotation()` in `OperationsHelper`.
 * Offline changes and client-to-server sync.
 * Demo that displays a JS alert with JSON representation of article annotations in the `ReadArticleActivity`. See `webview_htmlbase.html` and `JsAnnotationController` for details.

What's not done:
 * Proper testing.
 * Any UI:
   * HTML/JS-side for highlighting and interacting with annotations in text.
   * Android side for modifications (only annotation text can be modified) and maybe more if not implemented in JS.

I'm not yet sure, but it seems that annotation changes on the server side do not mark articles as modified, so **API clients never detect annotation changes**. If that's correct, it may become an impediment akin to server-side deleted articles. Except this one doesn't have a workaround.

Everyone is welcome to step in to help with UI and JS stuff.

#115.

### CODE REVIEW

**Comment by di72nn** [comment]
BTW, if anyone is interested, here are some code snippets I ran from `ReadArticleActivicy` using debug evaluation to test stuff:
```

**Comment by Strubbl** [comment]
When having annotation support, maybe we can add a menu item to the navigation drawer, which is called "Annotated" or the like. It shall filter for annotated articles. With the tabs we can then see the unread, starred or achived annotated articles.

**Comment by di72nn** [comment]
It sure is possible. However, a harder part is some kind of UI for displaying and creating annotations - without it this code is useless.

**Comment by di72nn** [comment]
Rebased. [Here's the old code](https://github.com/di72nn/wallabag-android-app/tree/annotations) just in case (github seems to save old commits, but I'm not bothered to check for how long).

**Comment by di72nn** [comment]
Here's a **very** clunky AnnotatorJS-based UI.
Short version: yes it kinda works, you can go ahead and test it.

Since I'm not a web developer at all, it was an absolute pain to do. ~~Through suffering~~I learned a lot.

For that reason I didn't even try to implement the JS part myself, so I had to resort to some libraries.

I considered using [touch plugin](https://github.com/aron/annotator.touch.js), which only works with AnnotatorJS `1.2`. I managed to get it running, but the UI didn't work that well with our webview (which always wraps the whole page instead of scrolling - the "annotate" button always appeared at the bottom of the article). I also couldn't build a proper version of AnnotatorJS 1.2 (some AnnotatorJS build scripts didn't work properly in my environment). Also I'm not very happy with using a version that ancient.

Instead I built AnnotatorJS's [master](https://github.com/openannotation/annotator). It is not mobile friendly, so I kludged it with Android's context menu action: you select text, press "Annotate" in the context menu, *then* annotator's "annotate" icon appears. That may be improved of course.
Another problem is that annotator popups often appear partly outside of the screen, not sure what's the deal with this.

Anyway, that last solution kinda works (UI wise; hopefully non-UI parts work ok).
**So anyone interested in this feature should now have more than enough examples to properly implement the UI.**

**Comment by di72nn** [comment]
Fixed "Annotate" not doing anything on real devices.

Removed that extra step: annotation editor appears directly after pressing "Annotate".
Made a lousy attempt to horizontally center annotator popups.

AnnotatorJS is built from [this branch](https://github.com/di72nn/annotator/tree/wallabag-android-app-changes) ([`npm install .`, `make`](https://github.com/openannotation/annotator/blob/master/HACKING.rst), take `pkg/annotator.min.js`).

**Comment by di72nn** [comment]
Seeing the flurry of activity I presume this is the best it's gonna get (I'm certainly not improving it much more), so I'm marking annotations as an "experimental feature", disabling it by default and unlabeling PR's "work in progress" status.

**Comment by di72nn** [comment]
Oh, I keep forgetting to thank @The-Compiler for #884 - remote WebView debugging was immensely useful, thank you!

**Comment by Strubbl** [comment]
I have installed this branch on my phone and i am going to test the feature.

**Comment by mberasategi** [comment]
THANK YOU! This is a real deal breaker. Really hope it can be made better, but **it works** is certainly enough to keep (at least me) from switching. 😍

**Comment by mblennegard** [comment]
I tried this out the other day and noticed that annotations made in the web application does not show up in the Android app.

Maybe this is what is supposed to happen at the moment, but otherwise I can create a bug or feature request respectively.

**Comment by Strubbl** [comment]
I am not sure, but my guess is that annotations are only synced to the app after a "full update" and not the default "fast update". It is a similar problem with the tags, e.g. #463

**Comment by mblennegard** [comment]
@Strubbl You are absolutely right.
I just tried it and can confirm that a Full Update from the Android app indeed fetches the annotations made from the web application.

What's interesting is that any annotations made in the Android app syncs with the fast update, as the Android made annotations show up directly in the web application.
Or is it that any _edits_, such as setting tags, making annotations etc., made in the Android app syncs back to the DB immediately?

**Comment by di72nn** [comment]
Created a new issue with some explanation: #1048.



> Or is it that any _edits_, such as setting tags, making annotations etc., made in the Android app syncs back to the DB immediately?

Changes made in the app are always synced ASAP.

**Pull request merged**
