### PR TITLE
V2 feed update task

### PR DESCRIPTION
**Pull request by Strubbl**
UpdateFeedTask for v2 working. So limited amount of articles are loaded (depending on your config setting in wallabag)

dependenyc to PR #204 and PR #207

### CODE REVIEW

**Comment by nicosomb** [comment]
You don't need to open a new PR with the same commits than your previous PR.

**Comment by Strubbl** [comment]
so how do i handle continous development? only with one PR?

**Comment by Strubbl** [comment]
closing due to PR #210 handling all v2 stuff

**Comment by di72nn** [comment]
> so how do i handle continous development? only with one PR and pushing always the same branch?

Yep. You can also add 'WIP' to the title to indicate 'work in progress' (as opposed to 'ready to merge').

**Pull request closed without merging**
