### PR TITLE
theme: define per theme icon colors

### LINKED ISSUE #337: Some icons in Sepia theme are white with too less contrast from background
Some icons in Sepia theme are white with too less contrast from background. Either they need to be in a darker color or they should have a border like the sharing button. For details please see attached images.

the list misses a dark add and reload button:
article-list

the article view misses a dark archive and fav button and maybe a complete dark share button:
article-view

### PR DESCRIPTION
**Pull request by Strubbl**
fixes #337

### CODE REVIEW

**Comment by Strubbl** [comment]
Thanks for the feedback. 👍

**Comment by di72nn** [comment]
Tested on Android 4.4.4 (API 19). The solarized and the dark themes look good. The light themes have white on white icons in lists (list_item.xml) - `icon_read` and `icon_favorite` should be dark for these themes.

**Comment by Strubbl** [comment]
Thanks a lot. That's a good catch. I have missed that. It's also wrong in Android 7

**Comment by Strubbl** [comment]
in Android 7 it is fixed now

**Comment by Strubbl** [comment]
If somebody could test all themes for article list and article view in Android 4 and there are no issue anymore, i would like to merge this one

**Pull request merged**
