### PR TITLE
Update lists

### PR DESCRIPTION
**Pull request by di72nn**
Adds "endless scrolling" instead of limited list. Memory may still be an issue.

Use `DiffUtil` to update lists partially.

I'm not completely sure about the implementation, so suggestions are welcome.

~~Also, I think I had an issue with the lists not being updated after actions like "open an article - add it to favorite - go back to lists". I couldn't reproduce it yet. I added logging of warning messages "fragment is null". I'm pretty sure it should either update list or log the warning. I have no idea why the fragments can be null after they were initialized (initially I thought, that it might be related to threading, but only the main thread is supposed to access fragments).~~ Probably fixed with 2630998.

Related issues:
* Basic search: partly #113.
* Sync queue before full update: #127.
* Sorting order: partly #17 and #42.

Testing needed.

### CODE REVIEW

**Comment by di72nn** [comment]
Added basic search (using SQL's `LIKE %search string%`) on article title and text.
Current list is updated on every search string change - not sure about performance.

**Comment by tcitworld** [comment]
Hmm. I guess it will provoke some performance issues with huge articles, some maybe limit to title for now. Anyway we'll probably propose a search API soon on the server so it will have to be integrated with it at some point.

**Comment by di72nn** [comment]
Added an option to reverse sort order. The UI part should probably be improved (as for now it is just a menu item that reads "Change sort order"). Suggestions welcome.

There is an issue that fragments reinit their lists after orientation change. It is not critical (slight delay), but I'll have to fix it.

**Comment by di72nn** [comment]
Started to use AsyncTask to update lists. Synchronization issues are possible.

**Comment by Strubbl** [comment]
is the read to review label still valid atm?

**Comment by di72nn** [comment]
I removed the async loading from this PR - now it is ready for review.

**Comment by tcitworld** [comment]
Looks good. Will review and eventually build tomorrow.

**Comment by di72nn** [comment]
@tcitworld 
> Hmm. I guess it will provoke some performance issues with huge articles, some maybe limit to title for now.

I forgot to answer that. It seemed to me that the performance was decent even on old devices, so I left it as is. I considered "powerful" search (being able to search in content) more important than minor performance issues (which don't affect anything but search). Though, anyone is free to improve the feature.

**Comment by tcitworld** [comment]
I tested and it was okay for me so I merged. :)

**Pull request merged**
