### PR TITLE
Some updates

### PR DESCRIPTION
**Pull request by di72nn**
* Includes #98 (which is based on "master" branch)
* Merged into "dev" branch
* Some improvements for FeedUpdater
* Article reading position save and restore (especially useful in case of screen orientation change)
* Minor changes

### CODE REVIEW

**Comment by di72nn** [comment]
* Merged in "main-list" branch (articles list as main app activity, pull-to-refresh).
* Option to prioritize Favorite articles in list.
* "Toggle Favorite" also toggles article status on server.
* Added "open random article" function.
* Made "accept all SSL certificates" optional (instead of default: always on).
* Made "high contrast text" optional.
* Added "article list limit" as an option.
* Maybe other minor changes.

**Comment by nicosomb** [comment]
What can we do to help you? Do you need beta testers?

**Comment by di72nn** [comment]
Some more updates:
* Login only when authorization is expired (instead of re-login before every request).
* Added a button to fill in UserID+Token from server (using username and password).
* Added ability to add URL to wallabag from ReadArticleActivity (dialog on click).
* Other minor changes.

@nicosomb testing wouldn't hurt.

**Comment by tcitworld** [comment]
I'll build it this week-end and try to publish the app on the Play Store directly.

**Comment by di72nn** [comment]
I believe there is testing to be done before publishing it. I don't use android app much (currently), so the app may not be suitable for everyday use.
BTW, f-droid allows to publish test versions.

**Comment by tcitworld** [comment]
Sure.

**Comment by tcitworld** [comment]
Hi,
Just tested and it's really amazing and impressive. :)
What do you want to do next ? I'll publish it in beta state asap.

Just a few ideas if you want some ;-) : 
* Can you do a more intuitive presentation to jump from unread/favorites/archived articles, as some material design apps do it (hamburger button or swipe) ?
* I've seen some problems with embed YouTube videos and javascript

* What's the difference between fast sync and regular sync ? uploading changes ?

Again, thank you so much. You totally rock !

**Pull request merged**
