### PR TITLE
Remove cancel menu item from ManageArticleTagsActivity. Fixes #448

### LINKED ISSUE #448: Remove button in manage tags view
In manage tags view, if you click the "..." button only shows a "cancel" button. This is the same as clicking the "left arrow". I think you should remove the  "..." button.

screenshot_2017-03-02-20-32-25

### PR DESCRIPTION
**Pull request by Sekhmet**
Remove cancel menu item from ManageArticleTagsActivity.

### CODE REVIEW

**Comment by di72nn** [comment]
Please avoid committing changes to unrelated code.

**Comment by Strubbl** [comment]
@di72nn i would be okay with that, because i see removing unnecessary newlines as an improvement. It reminds me of the [boy scout rule](http://programmer.97things.oreilly.com/wiki/index.php/The_Boy_Scout_Rule)

**Comment by di72nn** [comment]
Sorry, my comment doesn't reflect what I had in mind. I wanted to say: *in general* avoid committing unrelated *auto-formatted* code parts unless you're sure they really improve something.

I commented because it looked to me like auto-formatting: one line moved for no particular reason, one line break removed (which breaks visual alignment of attributes). If you intentionally made these changes, I accept it.

In general I prefer to make separate commits for functional and cosmetic (code formatting, etc.) changes. In this case the changes are minor and related to the edited part, so the previous sentence doesn't apply. But if you plan to reformat a whole file, make a separate commit.

I don't remember ever thinking it through, so I might be wrong about it.

**Comment by Sekhmet** [comment]
It was autoformatted because I'm used to formatting code before committing.
I think we should agree on unified code style because it's inconsistent (ie. some XML files use space before /> and others don't).

**Comment by di72nn** [comment]
Unfortunately we don't have code style defined. Considering the number of contributors it was never the priority.
If someone is willing to document it - go ahead. I will contribute to it, but I have no plans starting it from scratch anytime soon.

> It was autoformatted because I'm used to formatting code before committing.

As long as we don't have a code style we agreed on, I don't see how auto-formatting unrelated code (with some unknown code style) is a good idea. Hence my initial point.

**Comment by Sekhmet** [comment]
I updated it so unrelated code remains the same.

**Pull request merged**
