### PR TITLE
[WIP] Updated color scheme

### PR DESCRIPTION
**Pull request by Lokesh-Krishna**
This is with reference to the discussion at #317.

@di72nn I finally managed to figure it out and I couldn't have without you so thank you so much!

I edited the theme using the Theme Editor in Android Studio and this applied well on both, the Light and the Dark theme.

Is this an acceptable method of doing this or is this there a preferred method?

### CODE REVIEW

**Comment by di72nn** [comment]
My experience in Android UI/theming is very limited, so...

The colors in the "Light" theme seem fine.

The "Dark" theme have the same blue action bar (in the "Dark (high contrast)" theme it's black). So we probably need to explicitly set the color for the "Dark" theme.

Also we have [colors.xml](https://github.com/wallabag/android-app/blob/master/app/src/main/res/values/colors.xml), so we can put the values there.
And the Android Studio suggests to add `tools:ignore="PrivateResource"` because the values override something.

**Comment by Lokesh-Krishna** [comment]
I too got that message about adding `tools:ignore="Private Resources"` but I didn't understand where it should be added.

Who here has the most experience when it comes to UI? This is my first attempt at this so I could really use some advice. Will adding this to the colors.xml file have the same effect as this values.xml file?

**Comment by di72nn** [comment]
We should probably set colors the way other themes do it (https://github.com/wallabag/android-app/blob/master/app/src/main/res/values/styles.xml).
There are various guides ([example](https://developer.android.com/training/material/theme.html#ColorPalette)). I have no time to get into it right now.

**Comment by Lokesh-Krishna** [comment]
I'll go through the guide and try to make a pull request that is more in line with the other themes. Should I close this one then?

**Comment by di72nn** [comment]
I'm fine with this PR being open until a new one is created.

**Comment by Lokesh-Krishna** [comment]
I no longer have access to a system that can run Android Studio so would anybody else be interested in getting this done in the right manner?
I think I have picked the right colour so if it can only be implemented in a manner that fits in with the way that themes are currently specified then we should finally be good to go for the new icon.

**Pull request closed without merging**
