### PR TITLE
Migrate to AndroidX

### PR DESCRIPTION
**Pull request by msfjarvis**
This PR also upgrades dependencies and rewrites the Travis-CI configuration for faster builds

### CODE REVIEW

**Comment by di72nn** [comment]
Cool, thanks!
I'll try to review it soon.

**Comment by msfjarvis** [comment]
> Cool, thanks!
> I'll try to review it soon.

Awesome! Once this lands I'll start bringing in some UI improvements :)

P.S. A file like [this](https://github.com/msfjarvis/viscerion/blob/master/.github/CODEOWNERS) will automatically handle review requests for you.

**Comment by di72nn** [comment]
> Once this lands I'll start bringing in some UI improvements :)

That'd be great!

> P.S. A file like [this](https://github.com/msfjarvis/viscerion/blob/master/.github/CODEOWNERS) will automatically handle review requests for you.

Thanks for the tip, I'll keep it in mind.

**Comment by tcitworld** [comment]
Merged in #814

**Pull request closed without merging**
