### PR TITLE
Add UI to share articles (dev branch)

### PR DESCRIPTION
**Pull request by shtrom**
Ass per #62.

### CODE REVIEW

**Comment by tcitworld** [comment]
Could the title of the article be also be shared ? Seems it [should](https://github.com/shtrom/android-app/commit/a7684ef5707cbdfb8265cd98fd3f51d7e356abdb#diff-90817f28f871eb773dc83e2ecf7fca4eR131) be, but I don't have it when sharing to the messaging app (via emulator).
wallabag_android__dev_bug

**Comment by kevmeyer** [comment]
We could add it in front of the URL.

**Comment by shtrom** [comment]
On Mon, Jan 19, 2015 at 10:48:09AM -0800, Thomas Citharel wrote:
> Could the title of the article be also be shared ? Seems it [should](https://github.com/shtrom/android-app/commit/a7684ef5707cbdfb8265cd98fd3f51d7e356abdb#diff-90817f28f871eb773dc83e2ecf7fca4eR131) be, but I don't have it when sharing to the messaging app (via emulator).
> wallabag_android__dev_bug

Sharing it to K9 mail, the title is shared properly, as the subject for
the email.

-- 
Olivier Mehani <shtrom@ssji.net>
PGP fingerprint: 4435 CF6A 7C8D DD9B E2DE  F5F9 F012 A6E2 98C6 6655
Confidentiality cannot be guaranteed on emails sent or received unencrypted.

**Comment by tcitworld** [comment]
Yeah but I guess for « messaging » social networks (I'm thinking to Twitter in particular) it would be good to have it also in the content, right ?

**Comment by shtrom** [comment]
On Mon, Jan 19, 2015 at 03:34:06PM -0800, Thomas Citharel wrote:
> Yeah but I guess for « messaging » social networks (I'm thinking to
> Twitter in particular) it would be good to have it also in the
> content, right ?

This makes sense. I was also looking at a way to integrate  parts of the
article (e.g., first paragraph or so). I didn't find a quick way to do
it, so gave up on all the idea, and replicated what the web interface
does (;

But yeah, this shouldn't be hard to implement.

-- 
Olivier Mehani <shtrom@ssji.net>
PGP fingerprint: 4435 CF6A 7C8D DD9B E2DE  F5F9 F012 A6E2 98C6 6655
Confidentiality cannot be guaranteed on emails sent or received unencrypted.

**Pull request merged**
