### PR TITLE
Fix TTS icons in dark and solarized theme

### LINKED ISSUE #600: Dark theme issue: TTS icon
In dark themes, the icon for "read next article" is not visible (near the bottom checkbox)
screenshot_2017-07-01-09-04-08
. Should be white.

Related to dark theme: #552,  #599

### PR DESCRIPTION
**Pull request by NWuensche**
Working at #600

I have a problem with `attr`. I added a white running logo and the new theme attribute 
`icon_running`. However, android seems to ignore this and always takes the (dark) 
icon from the light theme. It does not use the attribute from the selected dark theme.

Can somebody please help me with this?

Edit: Closes #600 .

### CODE REVIEW

**Comment by di72nn** [comment]
It took me embarrassingly long time to figure out :man_facepalming: 
`values-v21/styles.xml` should be updated too. It solves #819 and makes #816 excessive.

**Comment by NWuensche** [comment]
Should I fix #816 too in a separate PR?

**Comment by di72nn** [comment]
I don't mind it being fixed in the same or a separate PR.

**Comment by NWuensche** [comment]
I will fix all the attributes stuff in #824 and also redo #816 there. After this is merged into master, I will work on this PR here again.

**Comment by NWuensche** [comment]
Everything is finished now.

**Pull request merged**
