### PR TITLE
Extract some strings to resources

### PR DESCRIPTION
**Pull request by di72nn**
@tcitworld what was the problem mentioned in 69dbabe?

### CODE REVIEW

**Comment by tcitworld** [comment]
My Android Studio (up-to-date) automatically wanted to remove untranslatable strings. Don't know why. You're right to put it pack though.

**Comment by di72nn** [comment]
Probably the same strings in `values-es` had something to do with it.

**Comment by Strubbl** [comment]
@di72nn  The strings in `values-es`? They were not touched in this PR. Is something wrong with them?

**Comment by di72nn** [comment]
@Strubbl check the commit I mentioned. The strings were both in `values` and `values-es` at the same time (marked `translatable="false"` in both files).

**Pull request merged**
