### PR TITLE
Add basic log export

### PR DESCRIPTION
**Pull request by di72nn**
Dumb logcat export: `Settings -> Miscellaneous -> Save logcat output to a file`.
#411.

### CODE REVIEW

**Comment by di72nn** [comment]
@tcitworld can we merge this and release another beta? #931 could have been in testing for more than a month already.

**Comment by Strubbl** [comment]
This feature works well. :+1:

**Comment by tcitworld** [comment]
Will do the release later today.

**Comment by di72nn** [comment]
Bump.

**Pull request merged**
