### PR TITLE
Adaptive icon

### PR DESCRIPTION
**Pull request by di72nn**
Somehow I didn't realize it was possible to make an adaptive icon with wallabag logo.

I took the [welcome.png](https://github.com/wallabag/android-app/raw/b15bfb16110e74d63240a8bd3c84dc56807ad240/app/src/main/res/drawable-mdpi/welcome.png) image, [cut out](https://github.com/wallabag/android-app/raw/b15bfb16110e74d63240a8bd3c84dc56807ad240/icon/wallabag.png) the relevant part, and used AndroidStudio's "New -> Image Asset" tool to create an adaptive icon (I used "Trim: No; Resize: 57%" for the foreground).

I know I was against replacing the icon with one for which we don't have sources (vector), but I was mostly against switching to a completely different style while not having sources for it. This PR merely replaces the old icon (for which we only have a PNG?) with an adaptive version of itself.

AndroidStudio also generated a separate round version (`roundIcon` in manifest), but it seems to be redundant if the foreground is the same (saved it [here](https://github.com/di72nn/wallabag-android-app/tree/adaptive_icon_with_round)).

Here are release and debug samples (these are prerendered for older APIs, adaptive versions take any shape):
Release Debug

### CODE REVIEW

**Comment by Strubbl** [comment]
It's saved as svg here: https://github.com/wallabag/logo/tree/master/_default/icon/svg

**Comment by di72nn** [comment]
@Strubbl great, thanks!

So I took one of the SVGs ([icon/logo-icon-black-no-bg.svg](https://github.com/wallabag/android-app/blob/e81bc9e079541c9fcdf8495d0734b69765e1ce56/icon/logo-icon-black-no-bg.svg)), did the same steps with AndroidStudio (except used Resize: 63%). Now the icon is actually in vector.
Then did the same to generate a debug icon from [icon/logo-icon-black-no-bg-debug.svg](https://github.com/wallabag/android-app/blob/e81bc9e079541c9fcdf8495d0734b69765e1ce56/icon/logo-icon-black-no-bg-debug.svg).
(And, of course, moved some files around to fit release/debug directory structure.)

Release Debug

I also have an SVG to create this debug icon, but I think red "w" is better:
ic_launcher

**Comment by Strubbl** [comment]
I like both icons. Does the widget look okay with the new icon?

**Comment by di72nn** [comment]
Good catch: the icon is too big for the widget. Widget layout probably needs some adjusting. I'll look into it later.

**Comment by di72nn** [comment]
Adjusted icon size a bit. I have no idea how it scales, but here's how it looks on my screen:
Screenshot
Legend:
F-Droid release icon | master release build icon | master debug build icon | none
---|---|---|---
F-Droid release widget | master release build widget | master debug build widget | master debug build icon (for vertical comparison)

**Pull request merged**
