### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by di72nn**
Translations from weblate.
In the last commit I fixed some minor stuff.

### CODE REVIEW

**Comment by di72nn** [comment]
I failed to notice that "wallabag" is stylized as all-lowercase name. Fixed it.

**Comment by tcitworld** [comment]
\o/

**Comment by nicosomb** [comment]
Oh, so you are weblate experts now.

**Comment by di72nn** [comment]
@tcitworld did you do anything on the weblate side (trigger rebase or something like that) or did it update by itself?

**Comment by tcitworld** [comment]
As I've done it, Weblate should automatically fetch changes on this repo **and** push changes to this repo.

**Comment by di72nn** [comment]
Push changes to this github repo?

**Comment by tcitworld** [comment]
Yup.

**Comment by di72nn** [comment]
That's kinda convenient, but I vote to disable it. It has at least two disadvantages:
 * Anyone with a Weblate account can save any strings on Weblate and consequently push the changes to the repo.
 * It can clutter history by committing at any time. With manual merges we can squash commits if needed.

Also we don't require frequent translation merges.

**Comment by tcitworld** [comment]
Indeed. I've disabled the push rights.

**Comment by di72nn** [comment]
Thank you.

**Pull request merged**
