### PR TITLE
update gradle

### PR DESCRIPTION
**Pull request by Strubbl**

### CODE REVIEW

**Comment by di72nn** [comment]
It does complain about support library versions mismatch, doesn't it?

**Comment by di72nn** [comment]
It does.
I've tried it earlier. Turns out the `compile 'com.mikepenz:aboutlibraries:5.7.3'` dependency pulls `com.android.support:cardview-v7:24.<something>` and gradle/android-plugin considers it as an error to have different versions of support libraries. I'm not sure whether it a bug or not (is [this](https://code.google.com/p/android/issues/detail?id=231324) it?), but I would suggest to postpone the update.

Anyway, I added `compile 'com.android.support:cardview-v7:25.2.0'` along the other support libs to dependencies to use explicitly the same version. It allows to build with the new gradle without errors.

**Comment by Strubbl** [comment]
Oh, local in my Android studio it did not complain...

**Comment by tcitworld** [comment]
Had the same issue but it didn't stopped me from building the app.

**Comment by di72nn** [comment]
Yeah, but it makes linter sad (and, consequently, CI checks).

**Comment by di72nn** [comment]
Consider "GradleCompatible" hint as warning until it is fixed in the android plugin.

**Comment by di72nn** [comment]
Or maybe we should add `compile 'com.android.support:cardview-v7:25.3.0'` to deps instead. That way the version is overridden and there's no errors or warnings.

**Comment by di72nn** [comment]
Changed my mind: added a fake dependency to explicitly set its version. The old branch is available as `update-gradle-bak`.

**Comment by Strubbl** [comment]
approved from my side (technically i cannot approve via github cause it is my PR)

**Pull request merged**
