### PR TITLE
 Dark theme #108 added

### PR DESCRIPTION
**Pull request by Caliandroid**
The commit b159155 contains the dark theme/night view #108 

commit 8a3fca3 should be ignored (only a gradle.build update).
I've added my app.iml -> should be ignored too

### CODE REVIEW

**Comment by Caliandroid** [comment]
I hadn't installed the gitignore plugin in android studio, that is why app.iml was not ignored

**Comment by tcitworld** [comment]
Thanks. I just made a modification for it to work also on list articles.

**Comment by tcitworld** [comment]
> I just made a modification for it to work also on list articles.

My bad, it's just it doesn't refresh.

**Comment by tcitworld** [comment]
I've made a workaround to avoid using `recreate()` and refresh without restarting the app.

**Comment by Caliandroid** [comment]
Thank you too for workaround.

**Pull request merged**
