### PR TITLE
Update Launcher Icon

### PR DESCRIPTION
**Pull request by lokesh-krishna**
I think this is all that's required to update the launcher icon. Is there anything more that has to be done? 

I haven't added round icon support because I don't know how that's done.

### CODE REVIEW

**Comment by OriginalFannibal** [comment]
Could someone please credit Michael Cook in the About screen so that the icon goes live only with the due credits?

**Comment by ngosang** [comment]
I love this icon!

**Comment by Strubbl** [comment]
Ah okay, i did not see this PR before creating my comment in #317. I am going to review it earliest by tomorrow night

**Comment by nicosomb** [comment]
Love it 😍

**Comment by OriginalFannibal** [comment]
Just want to add that we'll also need to update the icon in the sidebar and the About screen.  
Could somebody work on that?

**Comment by Strubbl** [comment]
@OriginalFannibal it should reference the same image as the logo for the app. therefore no need to adjust that code w.r.t new logo

**Comment by Strubbl** [comment]
oh, you mean https://github.com/wallabag/android-app/blob/master/app/src/main/res/drawable-mdpi/welcome.png and https://github.com/wallabag/android-app/blob/master/app/src/main/res/drawable-mdpi/welcome_white.png ?

**Comment by OriginalFannibal** [comment]
I didn't know they referenced the same resource. That does simplify things.  
Didn't know about these icons though :P  
How would one go about replacing the white one?

**Comment by OriginalFannibal** [comment]
Now that #317 has finally been cleared, can we merge this and #596? We would also need to replace the icons that @Strubbl mentioned but I don't know how to go about doing that.

**Comment by di72nn** [comment]
> Now that #317 has finally been cleared

Doesn't seem clear enough for me yet. I'll try to look into it soon.

BTW, last time I checked, a google guide recommended to place icons in a `mipmap` directory.

**Comment by OriginalFannibal** [comment]
@di72nn Michael has explained the situation regarding SVGs at #317. I am okay with closing this PR if someone can go the `mipmap` route. Would really love to see those icons on my phone as soon as possible!

**Comment by OriginalFannibal** [comment]
I found this when looking into the `mipmap` approach: [Mipmap and Drawables](https://stackoverflow.com/a/24066445/7214945)

Are we building separate APKs for each display density or a single one? If we have a single APK then I don't think we have anything to gain by going this route instead of just continuing with storing the icons in the `drawable` folder.

**Comment by lokesh-krishna** [comment]
Closed in favor of #638

**Pull request closed without merging**
