### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by di72nn**
* Better themes support (all activities; theme selection from list; better colors).
* Serif typeface for article fonts as an option (was: inconsistent, depending on main/nightmode.css).
* Font size for articles fonts option.

I'm not into CSS, so improvements are very welcome.
Font setting implementation is plain stupid, but, well, you are free to replace it anytime.

Update: icons color for dark themes **was not** fixed in this update.

### CODE REVIEW

**Comment by nicosomb** [comment]
Waiting for the new alpha! Really love this new app.

**Comment by tcitworld** [comment]
>  Font setting implementation is plain stupid, but, well, you are free to replace it anytime.

The best would be something like what Pocket does, just a +/- setting with preview. But for now, it's quite fine.


However, we've got to change the size of the spinner item, they are quite small to click on :

**Comment by nicosomb** [comment]
the 1st screenshot is a pocket one?

**Comment by tcitworld** [comment]
Yup, don't get your hopes to high for now.

**Comment by nicosomb** [comment]
so sad ;-)

**Pull request merged**
