### PR TITLE
Add configurable theme workaround for Onyx Boox devices

### PR DESCRIPTION
**Pull request by The-Compiler**
See https://github.com/wallabag/android-app/issues/168#issuecomment-593151010

Note that I'm not too familiar with Android development - I added all the XML stuff by hand, so it'd be good if someone could double-check that I didn't miss anything.

### CODE REVIEW

**Comment by di72nn** [comment]
There's a lot of potentially conflicting pending changes, so I guess I'll have to reintegrate this after #931.

**Comment by The-Compiler** [comment]
I'm happy to rebase and fix conflicts after that's in master, if needed.

**Comment by The-Compiler** [comment]
Rebased now that #931 was merged!

**Comment by di72nn** [comment]
I added some corrections [here](https://github.com/di72nn/wallabag-android-app/tree/The-Compiler-onyx-workaround). Can you merge/cherry-pick it into your branch and test that it still works?

**Comment by The-Compiler** [comment]
Pushed, thanks for the follow-up! Still seems to work fine.

**Pull request merged**
