### PR TITLE
Add a dialog for changing article title

### PR DESCRIPTION
**Pull request by di72nn**
#288.

### CODE REVIEW

**Comment by tcitworld** [comment]
Although sexy, this dialog isn't very handy with long titles since it doesn't allows viewing all of the content. Could it be possible to inject title edition in the tags management activity and make it a regular textarea ?

**Comment by di72nn** [comment]
How about multi-line textarea?

**Comment by tcitworld** [comment]
Works for me. I guess the title in the article should be updated right away but because of the way we do it it's necessary to reload the whole page.

**Comment by di72nn** [comment]
Yeah, we probably need to show the title outside WebView as an Android View (also reading time, tags, etc.). I thought it is better to include this feature even though the WebView is not updated yet.

**Comment by tcitworld** [comment]
👍

**Pull request merged**
