### PR TITLE
update gradle to 3.0.1 and wrapper to 4.1

### PR DESCRIPTION
**Pull request by Strubbl**

### CODE REVIEW

**Comment by Strubbl** [comment]
hmm, travis cannot find gradle3 ... ?

**Comment by tcitworld** [comment]
See https://stackoverflow.com/questions/44406647/android-o-gradle-build-fails-with-travis-ci ?

**Comment by Strubbl** [comment]
Ah cool. That might be a solution. But the stackoverflow question leaves open if gradle3 will be synced to jcenter some day.

**Comment by tcitworld** [comment]
I guess the order of repositories will be used then ?

**Comment by Strubbl** [comment]
I meant, let's wait until jcenter provides the gradle3. Or will that never happen?
This way we do not have to introduce another maven source then.

**Pull request merged**
