### PR TITLE
Fix #240 inflate exception toast text view

### LINKED ISSUE #240: NullPointerException causes InflateException: Binary XML file line #4: Error inflating class TextView
App-Version
    24

Android-Version
    Android 4.4

Gerät
    Galaxy Note II (t03g)

```
android.view.InflateException: Binary XML file line #4: Error inflating class TextView
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
	at android.view.LayoutInflater.inflate(Native Method)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.widget.Toast.makeText(Toast.java)
	at android.widget.Toast.makeText(Toast.java)
	at fr.gaulupeau.apps.Poche.network.tasks.AddLinkTask.onPostExecute(AddLinkTask.java:97)
	at fr.gaulupeau.apps.Poche.network.tasks.AddLinkTask.onPostExecute(AddLinkTask.java:22)
	at android.os.AsyncTask.finish(AsyncTask.java)
	at android.os.AsyncTask.access$600(AsyncTask.java)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java)
	at android.os.Handler.dispatchMessage(Handler.java)
	at android.os.Looper.loop(Looper.java)
	at android.app.ActivityThread.main(ActivityThread.java:5602)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at android.graphics.Rect.set(Rect.java:261)
	at com.android.internal.policy.impl.MultiPhoneWindow.initStackBound(MultiPhoneWindow.java:1142)
	at com.android.internal.policy.impl.MultiPhoneWindow.generateLayout(MultiPhoneWindow.java:424)
	at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3359)
	at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1886)
	at android.support.v7.app.AppCompatDelegateImplV7.shouldInheritContext(AppCompatDelegateImplV7.java:983)
	at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:970)
	at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:1030)
	at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
	... 24 more
```

### PR DESCRIPTION
**Pull request by Strubbl**
Shall fix #240. Please review. I am catching two exceptions here, is one of those catches unnecessary and too much? 

I could not reproduce this issue, therefore i couldn't test the fix.

### CODE REVIEW

**Comment by tcitworld** [comment]
I guess the `NullPointerException` should be enough, but we can't be sure in this case.

**Comment by di72nn** [comment]
If I understand the stacktrace correctly, you can't catch `NullPointerException` here (it's not even thrown here), and you should not catch `InflateException` because it means that something is wrong and we should fix a source of the problem. Maybe something wrong with context. The problem should be investigated.

**Comment by Strubbl** [comment]
@di72nn do you have any hint for investigation this problem?

**Comment by di72nn** [comment]
BTW, you shouldn't concatenate exceptions like that: `Log.w(TAG, "..." + e);`, you should pass the exception to the logger: `Log.w(TAG, "...", e);`. IIRC, you lose stacktrace in the former case.

**Comment by Strubbl** [comment]
@di72nn since merged #254 do we still need this code in this PR?

**Comment by di72nn** [comment]
No, we don't need it if #254 fixes the problem. Otherwise this PR maybe considered as *a temporary workaround*.

**Pull request closed without merging**
