### PR TITLE
Update launcher icon with flat long-shadow variant

### PR DESCRIPTION
**Pull request by lokesh-krishna**
As discussed at #317, here's the PR to update the app launcher icon. Round icon support hasn't been added and neither has support for adaptive icons. I don't know how to do either and I think we'll need Michael Cook's help for the latter with regards to a foreground and background layer unless someone here can do it.

All the `.png`s were generated using the provided `.svg`.

Also, as mentioned at #595, the icons need go into the `mipmap` directory only if we are building different apks for different display density (which I think we aren't).

Also, the discussion at #595 mentioned the welcome icons but I don't think they need changing because they represent the service while these icons represent one specific product based off that service. Also, they look better in that context. That's just my understanding of it and I will make a PR for them as well if someone feels that is required.

Someone will need to credit Michael Cook for the icon in the About screen so that the requisite credits are present when this icon goes live. This is how he said he would like to be credited:  

> If you'd like to include credits, please do something like: Michael Cook, http://cookicons.co

Would be nice if this was also mentioned in the changelog for the version in which this goes live for that's how I discovered him in the first place and I'd like to pay that forward.

### CODE REVIEW

**Comment by di72nn** [comment]
Can someone compare the app icon size to other app's icon sizes? If I understand correctly, icons should have some padding ([here](https://material.io/guidelines/style/icons.html#icons-system-icons) under the "Content area" caption).

See #645 for comparison.

**Comment by lokesh-krishna** [comment]
Finally looked into the link and my understanding of it is that the recommendation is regarding system icons. The padding is to protect the icon from getting cut off by elements such as sidebars, which is obviously not a problem for launcher icons.

Am I missing something?

**Comment by di72nn** [comment]
Yeah, it is about system icons, I didn't pay enough attention. I still have the impression that some padding is implied for launcher icons, but I can't find any numbers.

**Comment by lokesh-krishna** [comment]
Have you tested the icon? It would be nice to see what it looks like in action and see if it is fine the way it is now. 

I can't build apps on my current setup so it would be really nice if someone could and share some screenshots.

Seeing how the icon was made by someone who has made icons for plenty of others apps too, I think any requirements would already have been taken care of.

**Comment by lokesh-krishna** [comment]
Sorry about bumping but can someone please test the icons so that this can be merged?

**Comment by lokesh-krishna** [comment]
I'll gladly update the readme with the new icon and also add credit Michael Cook.   

I checked the debug icon and if you could provide me with a SVG of the same then I could move the bug to the new icon and update that as well.

Making changes to the About screen is beyond my skill set presently. 🙈 

As for the conflict with #645, that PR was opened to go with a version of this icon with added padding but I think I and @di72nn have arrived at an understanding regarding that. @di72nn, do you think it would be okay to close your PR?

**Comment by Strubbl** [comment]
Sorry, i forgot about #596. Thanks for the reminder. Thanks for adding credits to that PR.

The bug being used is the following unicode char: https://www.fileformat.info/info/unicode/char/1f41b/index.htm
You can also get the SVG from that site.

Currently, in the app we have navigation pane, which we can open from the left. There is also the official wallabag logo being used. But this logo we do not want to replace, don't we? 
We only want the Android app logo to be changed, correct?

If we have all those changes in here and #596, from my point of view, we can go ahead merging this. 
For the about screen i am going to open up an issue for adding the graphics credits.

**Comment by lokesh-krishna** [comment]
Added a debug icon and added credits for the icon in #596.

**Comment by lokesh-krishna** [comment]
Sorry about bumping but can we please move ahead with this?

**Comment by lokesh-krishna** [comment]
I have figured out how to add support for adaptive icons and would like to open a new PR with adaptive icon support. I hope it is okay to close this one.

**Comment by Strubbl** [comment]
Yes, no problem @lokesh-krishna . Thanks a lot for your ongoing commitment and contribution to the project

**Pull request closed without merging**
