### PR TITLE
Show last update time in navigation drawer header

### LINKED ISSUE #303: Show last update time
Show somewhere the time of last (auto-)update.

### PR DESCRIPTION
**Pull request by di72nn**
Alternative to #335.
Fixes #303.

For some reason I failed to apply themed color for `android:textColor`, so I set gray color that is visible on both light and dark backgrounds.

### CODE REVIEW

**Comment by nicosomb** [comment]
Screenshot ?

**Comment by di72nn** [comment]
I'm not sure about the color and margins/padding.

**Comment by Strubbl** [comment]
@nicosomb 
screenshot attached:

screenshot_20170606-190038

I would align the text to left or center it.

**Comment by ngosang** [comment]
I prefer this location instead of #335. Could we make the wallabag logo in sidebar smaller?

**Comment by Strubbl** [comment]
@ngosang Yes, but not in this PR i guess. You already refered to moving the fav and archived tabs to the side bar. While implementing this, it would be a good chance to reorganize the side bar.

**Comment by Strubbl** [comment]
@di72nn From my point of view, this PR can be merged now.

**Pull request merged**
