### PR TITLE
Feature 696: Show Password

### PR DESCRIPTION
**Pull request by kpchungdev**
Added Show Password feature to Configuration Screens.

### CODE REVIEW

**Comment by kpchungdev** [comment]
I am new to Github. Would squashing my commits into one mean pulling requests again with squashed commits?

**Comment by Strubbl** [comment]
No, you can reuse your existing branch. But of course, if you want to try out before working on your important branch, you can also branch again from your feature-696-show-password branch and try everything in that test branch until you are satisfied.

If you are in your branch, you can use `git rebase -i master`, then you can squash commit 2 to 18 and only pick the first one. After you are done, you can force-push your branch feature-696-show-password to your repository kpchungdev/android-app.

You can find some documentation about that process at https://git-scm.com/docs/git-rebase#_interactive_mode

**Comment by kpchungdev** [comment]
I squashed 2 to 18 commits and picked the first commit.

**Comment by Strubbl** [comment]
Hmm, something did not work out as expected, because instead of one commit containing all changes of this PR, we have in sum 20 commits in this PR.

**Comment by Strubbl** [comment]
The commit https://github.com/wallabag/android-app/pull/697/commits/486b6c3ef9d8de0734bae50e2964bdd246b9b41f you created has all changes in. But we still have the 18 commits from before. Also the second new (20th) commit is a merge. This merge is not needed.

**Comment by kpchungdev** [comment]
I think it'll be easier if you use Github squash+merge for me.

**Comment by Strubbl** [comment]
Nice, you made it. Thank you very much for squashing.
I am going to wait for a feedback of @di72nn before this PR is going to be merged.

**Comment by di72nn** [comment]
Hi!

Thank you for your contribution and sorry for the delay in replying.

I would suggest to replace this:
```Java
if (isChecked) {
    inputType = InputType.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD;
} else {
    inputType = 129;
}
```
with this:
```Java
if (isChecked) {
    inputType = InputType.TYPE_CLASS_TEXT | InputType.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD;
} else {
    inputType = InputType.TYPE_CLASS_TEXT | InputType.TYPE_TEXT_VARIATION_PASSWORD;
}
```

I replaced `129` with its equivalent and added `InputType.TYPE_CLASS_TEXT` to the first assignment just in case.

**However**, I found out that you can use [this method](https://stackoverflow.com/questions/3685790/how-to-switch-between-hide-and-view-password/39022642#39022642) to achieve similar result simply by adding `app:passwordToggleEnabled="true"` to the layout file. I suggest to go this way, because it is simpler and does not require translations.

**Comment by kpchungdev** [comment]
Yeah that method sounds way better.

**Comment by di72nn** [comment]
@kpchungdev are you interested in implementing it the other way?

**Comment by ngosang** [comment]
I didn't tested it fully, but in Android 7.0 I don't see any change in password text boxes..

**Comment by kpchungdev** [comment]
Uhh sorry. I had misunderstood git. I force pushed my changes and it should work now. No checkbox but edittext's native show password icon.

**Comment by Strubbl** [comment]
@kpchungdev wrote:

> Ended up doing feature branch -> reset to branch to master -> add passwordtoggle in feature branch which required a force push.

Just create a new branch and push that. Finally open up a new Pull request in this project. We can close this old one then.

**Pull request closed without merging**
