### PR TITLE
Suggest all available tags if no filter

### PR DESCRIPTION
**Pull request by makuto**
This makes it much easier to tag articles with tags you've entered before.

### CODE REVIEW

**Comment by di72nn** [comment]
Squashed the original commits and then simplified the logic.

**Comment by di72nn** [comment]
Oh, and thanks for improving this functionality @makuto!

**Comment by di72nn** [comment]
Also reworked layout a bit. The element order now as follows:
1. Selected tags.
1. Text field + button.
1. Suggested tags.

My UI skills suck, so you may revert or further improve it.

**Comment by makuto** [comment]
Do I close this now or does someone else merge and close it?

**Pull request merged**
