### PR TITLE
Replace "bag it" strings

### PR DESCRIPTION
**Pull request by di72nn**
I has been bothering me for quite some time. I've never liked this jargon. Is it just me?

### CODE REVIEW

**Comment by tcitworld** [comment]
Suits me, even though [this](https://www.wired.com/2017/02/diehard-coders-just-saved-nasas-earth-science-data/) made me think it was a good choice afterwards. But this should be a collective decision in every app.

@wallabag/contributors @wallabag/core @wallabag/translators Okay to drop the `bag it !` sentence and replace it by `add to wallabag` (or something else) ?

**Comment by matteocoder** [comment]
I'm fine with it, but it might be confusing for a new user. If we want to keep it maybe we should add a little tutorial when the app starts up for the first time.

**Comment by di72nn** [comment]
BTW, does any other wallabag app or add-on use "bag it"?

**Comment by Rurik19** [comment]
@di72nn wallabagger has "Wallabag it!" menu item

**Comment by matteocoder** [comment]
Now that I think about it, "add to wallabag" is a lot more translation friendly than "Bag it".

**Comment by jlnostr** [comment]
The translation by Pocket which is just "+Pocket" is not an option IMO. "Add to wallabag" is the best string to use here, at least in my opinion.

**Comment by j0k3r** [comment]
Add to wallabag is good to me.
"Bag it!" is fun, but we don't really know who's behind. What kind of service wil be used.
Also, if people put link "add to wallabag" all over the web, more people will check for that name instead of "bag" (from "bag it")

**Comment by ngosang** [comment]
I prefer just "Wallabag" instead of "Add to wallabag". 

The Android share dialog looks like this:

**Comment by Strubbl** [comment]
> I prefer just "Wallabag" instead of "Add to wallabag".

I agree. As long as we have only one sharing dialog option, i prefer that short variant, too.

**Comment by di72nn** [comment]
I have "Add to Firefox", "Add to Pocket", "Add to Shaarli" at the top of my share list. Keep in mind that "Wallabag" would be somewhere near the bottom of the list.

**Comment by ngosang** [comment]
In my Android they are sorted by use, most used at top. Anyway I don't care so much, both names are good to me.

**Comment by bourvill** [comment]
Only "wallabag" sound good

**Comment by nicosomb** [comment]
It's wallabag. Period. 😬

**Comment by di72nn** [comment]
I take it the majority is in favor of plain "wallabag", right?

**Comment by matteocoder** [comment]
The boss has spoken his will. It shall be "wallabag"

**Comment by di72nn** [comment]
Updated to "wallabag". Also marked it untranslatable.

**Comment by matteocoder** [comment]
@di72nn I see that there are quite a few changes in your commit, what should I do when the Italian translation gets merged?

**Comment by di72nn** [comment]
@matteocoder that depends on the order in which the PRs will get merged. You'll be notified if we'll need you to change something.

**Pull request merged**
